### ISSUE TITLE
GLIBC 2.17 not found

### ISSUE THREAD

**Issue by rainwoodman** [conda-forge/tensorflow-feedstock#11]
I am quite new to conda-forge. It looks like a problem on my end -- there must be a very simple fix to this? Could someone give some light? Thanks.

```
bash-4.1$ python                                                                                                                      
impPython 3.5.1 |Anaconda custom (64-bit)| (default, Dec  7 2015, 11:16:01)                                                           
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux                                                                                       
Type "help", "copyright", "credits" or "license" for more information.                                                                
>>> import tensorflow                                                                                                                 
Traceback (most recent call last):                                                                                                    
  File "<stdin>", line 1, in <module>                                                                                                 
  File "/project/projectdirs/m779/yfeng1/envs/tensorflow/lib/python3.5/site-packages/tensorflow/__init__.py", line 23, in <module>    
    from tensorflow.python import *                                                                                                   
  File "/project/projectdirs/m779/yfeng1/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 48, in <modu
le>                                                                                                                                   
    from tensorflow.python import pywrap_tensorflow                                                                                   
  File "/project/projectdirs/m779/yfeng1/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28,
 in <module>                                                                                                                          
    _pywrap_tensorflow = swig_import_helper()                                                                                         
  File "/project/projectdirs/m779/yfeng1/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24,
 in swig_import_helper                                                                                                                
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)                                                           
  File "/project/projectdirs/m779/yfeng1/envs/tensorflow/lib/python3.5/imp.py", line 242, in load_module                              
    return load_dynamic(name, filename, file)                                                                                         
  File "/project/projectdirs/m779/yfeng1/envs/tensorflow/lib/python3.5/imp.py", line 342, in load_dynamic                             
    return _load(spec)                                                                                                                
ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /project/projectdirs/m779/yfeng1/envs/tensorflow/lib/python
3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so) 
```

**Comment by jjhelmus** [comment]
@rainwoodman What version/distrobution of Linux are you trying to run this on?  The conda-forge tensorflow package requires Ubunutu 14.04 or newer as we are currently repackaging the tensorflow whl files provided by Google.  

Building the package from source, #6, may allow the package to work on Linux installs with older version of glibc.

**Comment by rainwoodman** [comment]
Thanks. I think it is a CentOS 6.8. The libc is kinda old. Indeed building from source on the platform we use will solve the problem. There are too many dependencies and it looks scary though.

**Comment by jakirkham** [comment]
So if we can get this built from source, the binaries should work on CentOS 6.8. We target CentOS 6 as an org.

**Comment by jjhelmus** [comment]
If you want to try the tensorflow 0.10.0rc0 packages from [my, jjhelmus, channel](https://anaconda.org/jjhelmus/tensorflow/files) the lastest build, 1, was built in a CentOS 6 Docker container and should work with older versions of libc.

**Comment by rainwoodman** [comment]
Yes
```
conda install -c jjhelmus tensorflow 
```
fixes the problem at import. Is there a way to run the tests? I tried `tensorflow.test.main()` but it found zero cases.

**Comment by rainwoodman** [comment]
This is how it looks:

```
>>> from  tensorflow import test                                                                   
>>> test.                                                                                          
test.Benchmark(               test.__le__(                  test.compute_gradient(                 
test.TestCase(                test.__loader__               test.compute_gradient_error(           
test.__all__                  test.__lt__(                  test.device_lib                        
test.__cached__               test.__name__                 test.division                          
test.__class__(               test.__ne__(                  test.get_temp_dir(                     
test.__delattr__(             test.__new__(                 test.googletest                        
test.__dict__                 test.__package__              test.is_built_with_cuda(               
test.__dir__(                 test.__reduce__(              test.is_gpu_available(                 
test.__doc__                  test.__reduce_ex__(           test.main(                             
test.__eq__(                  test.__repr__(                test.make_all(                         
test.__file__                 test.__setattr__(             test.mock                              
test.__format__(              test.__sizeof__(              test.print_function                    
test.__ge__(                  test.__spec__                 test.sys                               
test.__getattribute__(        test.__str__(                 test.test_src_dir_path(                
test.__gt__(                  test.__subclasshook__(        test.test_util                         
test.__hash__(                test.absolute_import                                                 
test.__init__(                test.assert_equal_graph_def(                                         
>>> test.main()                                                                                    
                                                                                                   
----------------------------------------------------------------------                             
Ran 0 tests in 0.000s                                                                              
```

**Comment by jjhelmus** [comment]
I do not believe you can run tensorflow's unit tests with the installed package, rather it [seems like you must use bazel](http://stackoverflow.com/questions/34204551/run-tensorflow-unit-tests) along with the source code.

**Comment by rainwoodman** [comment]
Thanks. I'll probably copy and run an example to see if it really works. Do you recommend an alternative? I am fully new to this (just starting to follow the tutorial).

**Comment by rainwoodman** [comment]
I can confirm the first example on the tutorial works with this build. I am closing this for now. Thanks again for building this!

**Comment by smithsp** [comment]
@jjhelmus I came across this problem, but your channel's build is version 0.5 (which was the resolution of this problem).  Any chance you can rebuild a newer version?

**Comment by jjhelmus** [comment]
> Any chance you can rebuild a newer version?

I work for Anaconda, Inc now and help build the packages which go into the defaults channel.  The tensorflow packages available there will work on system with glibc 2.12 and above.

**Comment by smithsp** [comment]
Where should I open an issue?

**Comment by jjhelmus** [comment]
> Where should I open an issue?

Sorry I don't follow.  Tensorflow packages which support glib 2.12 and above as new as version 1.7.0 are available in the `defaults` channel.  

Issue #6 is conda-forge's progress on building from source which would produce packages with a similar level of support for glibc versions.

**Comment by smithsp** [comment]
@jjhelmus Thanks for your prompt attention, and thanks for the hint that I needed to make sure to use the `defaults` channel, as I had added the `conda-forge` channel with higher priority.  

As a side note to possible others: I had to install the `protobuf` package after that, even though it was already installed, as I found somewhere that the tensorflow package might have a namespace collision with a separate `google.protobuf`package available with the `protobuf` conda package.

**Comment by Ic3fr0g** [comment]
`conda install -c jjhelmus/label/tflow_110_testing tensorflow` installs tensorflow with GPU. Can you kindly create a version for CPU only.
Thanks for this, it's great for RHEL and old GLIBC versions.

**Comment by jjhelmus** [comment]
A cpu only version is available in the `defaults` channel.
