### ISSUE TITLE
Upload from cirun server fails

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/tensorflow-feedstock#390]
Unfortunately, while #385 had green CI in the PR (and the packages build successfully), it [fails](https://github.com/conda-forge/tensorflow-feedstock/actions/runs/9207678000/job/25328256975) during package upload:
```
Using STAGING_BINSTAR_TOKEN for anaconda.org uploads to cf-staging.
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Adding in variants from /home/conda/recipe_root/conda_build_config.yaml
Adding in variants from /home/conda/feedstock_root/.ci_support/linux_64_c_compiler_version12c_stdlib_version2.12cuda_compilerNonecuda_compiler_versionNonecxx_compiler_version12python3.11.____cpython.yaml
[ERROR] 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 457, in get_release
    self.api.release(self.username, meta.name, meta.version)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/__init__.py", line 424, in release
    self._check_response(res)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/__init__.py", line 229, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ("release version='2.16.1' does not exist", 404)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/scripts/cli.py", line 257, in main
    binstar_main(commands, args, exit_)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/scripts/cli.py", line 206, in binstar_main
    return arguments.main(arguments)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 61, in main
    uploader.upload(filename)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 504, in upload
    return self.upload_package(filename, package_meta)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 537, in upload_package
    self.get_release(meta)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 473, in get_release
    self.api.add_release(self.username, meta.name, meta.version, [], announce, meta.release_attrs)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/__init__.py", line 464, in add_release
    self._check_response(res)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/__init__.py", line 229, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.Unauthorized: ('Authorization token is no longer valid', 401)
Failed to upload due to Command '['anaconda', '--quiet', '--show-traceback', '-t', '/tmp/tmp5nhy5lju/binstar.token', 'upload', '/home/conda/feedstock_root/build_artifacts/linux-64/libtensorflow_cc-2.16.1-cpu_hb0d1dac_0.conda', '--user=cf-staging', '--channel=main', '--force-metadata-update']' returned non-zero exit status 1.. Trying again in 10 seconds
```

I've cancelled the remaining runs to avoid wasting resources. Does this need a token rotation somewhere? On admin-requests or in https://github.com/conda-forge/.cirun somewhere?

CC @jaimergp @isuruf

**Comment by isuruf** [comment]
This repository had a STAGING_BINSTAR_TOKEN for some reason added 2 years ago. Deleted it.

**Comment by h-vetinari** [comment]
Thank you!
