### ISSUE TITLE
import tensorflow ---> ImportError in version 1.8.0

### ISSUE THREAD

**Issue by tundo91** [conda-forge/tensorflow-feedstock#57]
Issue:
```
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/miniconda/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/miniconda/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/miniconda/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: /miniconda/lib/python3.6/site-packages/google/protobuf/pyext/_message.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb
```

<br/>
Dockerfile:
<details>

```
FROM ubuntu:16.04
MAINTAINER HAL24K "docker@hal24k.com"

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    unzip \
    yasm \
    pkg-config \
    curl

# install conda
RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p /miniconda
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH=/miniconda/bin:${PATH}
RUN echo PATH=/miniconda/bin:${PATH} >> ./bashrc

# install opencv from conda
# NOTE as of 11-07-2018, conda-forge's opencv==3.4.1 doesnt install the python wrapper around OpenCV
# issue: https://github.com/conda-forge/opencv-feedstock/issues/111
RUN conda install -y --verbose -c anaconda opencv==3.4.1
RUN conda install -y --verbose -c conda-forge tensorflow==1.8.0
ARG https_proxy
ARG http_proxy

## Cleanup
RUN rm -rf /var/lib/apt/lists/*

# Python dependencies
RUN pip --no-cache-dir install \
    py3nvml \
    azure \
    logzero==1.5.0


WORKDIR /src

RUN mkdir /data
RUN mkdir /data/models
RUN mkdir /data/sample_videos

COPY settings.py /src/settings.py
COPY fetch_azure_blobs.py /src/fetch_azure_blobs.py
COPY examples /src/examples
COPY playback /src/playback
COPY deps /src/deps

RUN python -u /src/fetch_azure_blobs.py
```
</details>

<br/>
Environment (<code>conda list</code>):

<details>

```
$ conda list
# packages in environment at /miniconda:
#
# Name                    Version                   Build  Channel
absl-py                   0.2.2                      py_0    conda-forge
adal                      1.0.2                     <pip>
asn1crypto                0.24.0                   py36_0  
astor                     0.6.2                      py_0    conda-forge
azure                     3.0.0                     <pip>
azure-batch               4.1.3                     <pip>
azure-common              1.1.13                    <pip>
azure-cosmosdb-nspkg      2.0.2                     <pip>
azure-cosmosdb-table      1.0.4                     <pip>
azure-datalake-store      0.0.22                    <pip>
azure-eventgrid           0.1.0                     <pip>
azure-graphrbac           0.40.0                    <pip>
azure-keyvault            0.3.7                     <pip>
azure-mgmt                2.0.0                     <pip>
azure-mgmt-advisor        1.0.1                     <pip>
azure-mgmt-applicationinsights 0.1.1                     <pip>
azure-mgmt-authorization  0.30.0                    <pip>
azure-mgmt-batch          5.0.1                     <pip>
azure-mgmt-batchai        0.2.0                     <pip>
azure-mgmt-billing        0.1.0                     <pip>
azure-mgmt-cdn            2.0.0                     <pip>
azure-mgmt-cognitiveservices 2.0.0                     <pip>
azure-mgmt-commerce       1.0.1                     <pip>
azure-mgmt-compute        3.0.1                     <pip>
azure-mgmt-consumption    2.0.0                     <pip>
azure-mgmt-containerinstance 0.3.1                     <pip>
azure-mgmt-containerregistry 1.0.1                     <pip>
azure-mgmt-containerservice 3.0.1                     <pip>
azure-mgmt-cosmosdb       0.3.1                     <pip>
azure-mgmt-datafactory    0.4.0                     <pip>
azure-mgmt-datalake-analytics 0.3.0                     <pip>
azure-mgmt-datalake-nspkg 2.0.0                     <pip>
azure-mgmt-datalake-store 0.3.0                     <pip>
azure-mgmt-devtestlabs    2.2.0                     <pip>
azure-mgmt-dns            1.2.0                     <pip>
azure-mgmt-eventgrid      0.4.0                     <pip>
azure-mgmt-eventhub       1.2.0                     <pip>
azure-mgmt-hanaonazure    0.1.1                     <pip>
azure-mgmt-iothub         0.4.0                     <pip>
azure-mgmt-iothubprovisioningservices 0.1.0                     <pip>
azure-mgmt-keyvault       0.40.0                    <pip>
azure-mgmt-loganalytics   0.1.0                     <pip>
azure-mgmt-logic          2.1.0                     <pip>
azure-mgmt-machinelearningcompute 0.4.1                     <pip>
azure-mgmt-managementpartner 0.1.0                     <pip>
azure-mgmt-marketplaceordering 0.1.0                     <pip>
azure-mgmt-media          0.2.0                     <pip>
azure-mgmt-monitor        0.4.0                     <pip>
azure-mgmt-msi            0.1.0                     <pip>
azure-mgmt-network        1.7.1                     <pip>
azure-mgmt-notificationhubs 1.0.0                     <pip>
azure-mgmt-nspkg          2.0.0                     <pip>
azure-mgmt-powerbiembedded 1.0.0                     <pip>
azure-mgmt-rdbms          0.1.0                     <pip>
azure-mgmt-recoveryservices 0.2.0                     <pip>
azure-mgmt-recoveryservicesbackup 0.1.1                     <pip>
azure-mgmt-redis          5.0.0                     <pip>
azure-mgmt-relay          0.1.0                     <pip>
azure-mgmt-reservations   0.1.0                     <pip>
azure-mgmt-resource       1.2.2                     <pip>
azure-mgmt-scheduler      1.1.3                     <pip>
azure-mgmt-search         1.0.0                     <pip>
azure-mgmt-servermanager  1.2.0                     <pip>
azure-mgmt-servicebus     0.4.0                     <pip>
azure-mgmt-servicefabric  0.1.0                     <pip>
azure-mgmt-sql            0.8.6                     <pip>
azure-mgmt-storage        1.5.0                     <pip>
azure-mgmt-subscription   0.1.0                     <pip>
azure-mgmt-trafficmanager 0.40.0                    <pip>
azure-mgmt-web            0.34.1                    <pip>
azure-nspkg               2.0.0                     <pip>
azure-servicebus          0.21.1                    <pip>
azure-servicefabric       6.1.2.9                   <pip>
azure-servicemanagement-legacy 0.20.6                    <pip>
azure-storage-blob        1.3.0                     <pip>
azure-storage-common      1.3.0                     <pip>
azure-storage-file        1.3.0                     <pip>
azure-storage-nspkg       3.0.0                     <pip>
azure-storage-queue       1.3.0                     <pip>
blas                      1.0                         mkl    anaconda
bleach                    1.5.0                    py36_0    conda-forge
bzip2                     1.0.6                h14c3975_5    anaconda
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.12              h7636065_2    anaconda
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5           py36h9745a5d_0  
chardet                   3.0.4            py36h0f667ec_1  
conda                     4.5.8                    py36_0    conda-forge
conda-env                 2.6.0                h36134e3_1  
cryptography              2.2.2            py36h14c3975_0  
entrypoints               0.2.3                     <pip>
ffmpeg                    4.0                  h04d0a96_0    anaconda
fontconfig                2.12.6               h49f89f6_0    anaconda
freetype                  2.8                  hab7d2ae_1    anaconda
futures                   3.1.1                     <pip>
gast                      0.2.0                      py_0    conda-forge
glib                      2.56.1               h000015b_0    anaconda
graphite2                 1.3.11               h16798f4_2    anaconda
grpcio                    1.12.1           py36hdbcaa40_0  
harfbuzz                  1.7.6                h5f0a787_1    anaconda
hdf5                      1.10.2               hba1933b_1    anaconda
html5lib                  0.9999999                py36_0    conda-forge
icu                       58.2                 h9c2bf20_1    anaconda
idna                      2.6              py36h82fb2a8_1  
intel-openmp              2018.0.3                      0    anaconda
isodate                   0.6.0                     <pip>
jasper                    1.900.1              hd497a04_4    anaconda
jeepney                   0.3.1                     <pip>
jpeg                      9b                   h024ee3a_2    anaconda
keyring                   13.2.1                    <pip>
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran-ng            7.2.0                hdf63c60_3    anaconda
libopencv                 3.4.1                h1a3b859_1    anaconda
libopus                   1.2.1                hb9ed12e_0    anaconda
libpng                    1.6.34               hb9fc6fc_0    anaconda
libprotobuf               3.5.2                h6f1eeef_0    anaconda
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he85c1e1_1    anaconda
libvpx                    1.7.0                h439df22_0    anaconda
libxcb                    1.13                 h1bed415_1    anaconda
libxml2                   2.9.8                h26e45fe_1    anaconda
logzero                   1.5.0                     <pip>
markdown                  2.6.11                     py_0    conda-forge
mkl                       2018.0.3                      1    anaconda
mkl_fft                   1.0.1            py36h3010b51_0    anaconda
mkl_random                1.0.1            py36h629b387_0    anaconda
msrest                    0.5.3                     <pip>
msrestazure               0.4.34                    <pip>
ncurses                   6.1                  hf484d3e_0  
numpy                     1.14.5           py36hcd700cb_3    anaconda
numpy-base                1.14.5           py36hdbf6ddf_3    anaconda
oauthlib                  2.1.0                     <pip>
opencv                    3.4.1            py36h6fd60c2_2    anaconda
openssl                   1.0.2o                        0    conda-forge
pcre                      8.42                 h439df22_0    anaconda
pip                       10.0.1                   py36_0  
pixman                    0.34.0               hceecf20_3    anaconda
protobuf                  3.5.2                    py36_0    conda-forge
py-opencv                 3.4.1            py36h0676e08_1    anaconda
py3nvml                   0.2.0                     <pip>
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.18             py36hf9f622e_1  
PyJWT                     1.6.4                     <pip>
pyopenssl                 18.0.0                   py36_0  
pysocks                   1.6.8                    py36_0  
python                    3.6.5                hc3d631a_2  
python-dateutil           2.7.3                     <pip>
readline                  7.0                  ha6073c6_4  
requests                  2.18.4           py36he2e5f8d_1  
requests-oauthlib         1.0.0                     <pip>
ruamel_yaml               0.15.37          py36h14c3975_2  
SecretStorage             3.0.1                     <pip>
setuptools                39.2.0                   py36_0  
six                       1.11.0           py36h372c433_1  
sqlite                    3.23.1               he433501_0  
tensorboard               1.8.0                    py36_1    conda-forge
tensorflow                1.8.0                    py36_1    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.7                hc745277_3  
urllib3                   1.22             py36hbe7ace6_0  
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.31.1                   py36_0  
xmltodict                 0.11.0                    <pip>
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zlib                      1.2.11               ha838bed_2  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
```

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.8
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /miniconda/pkgs
                          /root/.conda/pkgs
       envs directories : /miniconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.8 requests/2.18.4 CPython/3.6.5 Linux/4.4.0-119-generic ubuntu/16.04 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

**Comment by jjhelmus** [comment]
Can you try installing **libprotobuf** from the `conda-forge` channel rather than `anaconda`?  The two use different C++ ABIs which are incompatible.

**Comment by tundo91** [comment]
Indeed, installing both opencv and tensorflow from the same channel would work.

**Comment by belvederef** [comment]
What worked for me was to install tensorflow from the conda-forge channel with:
```
conda install tensorflow -c conda-forge -f
```
