### ISSUE TITLE
Builds Generated On 08/22 are broken

### ISSUE THREAD

**Issue by lilleswing** [conda-forge/tensorflow-feedstock#82]
Issue:
Builds Generated after 08/22 are broken.  You can tell just by looking at the size of the packages.  Can you remove them from conda-forge?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jjhelmus** [comment]
`tensorflow` is now a metapackage which required `tensorflow-base`.  Have you run into issues with this new layout?

**Comment by lilleswing** [comment]
Yes starting last night.... at 12:30 AM  EST right after the new osx packages were released.

Installed on a fresh conda with the following command....

```
conda install -y -q  -c rdkit -c anaconda -c conda-forge "requests>=2.18.4" "matplotlib>=3.0" "xgboost>=0.81" "setuptools>=39.0.1" "pexpect>=4.6.0" "joblib=0.11" "rdkit>=2019.03.3.0" "scikit-learn>=0.20.0" "scipy>=1.2.0" "pandas>=0.23.4" "coverage" "nose>=1.3.7" "nose-timer" "python>=3.6" "jupyter" "tensorflow==1.13.1"
```

It isn't bringing in estimator.

```
Traceback (most recent call last):
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/ligand_ml/__init__.py", line 9, in <module>
    from .smasher import Smasher
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/ligand_ml/smasher.py", line 22, in <module>
    from ligand_ml.train_from_hps import ensemble_eval, max_min_ensemble, \
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/ligand_ml/train_from_hps.py", line 19, in <module>
    from ligand_ml.models.models import Model
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/ligand_ml/models/__init__.py", line 2, in <module>
    from ligand_ml.models.tensorflow.fcnet import MultitaskRegressor, MultitaskClassifier
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/ligand_ml/models/tensorflow/fcnet.py", line 10, in <module>
    from ligand_ml.models.tensorflow import activations
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/ligand_ml/models/tensorflow/activations.py", line 9, in <module>
    from ligand_ml.models.tensorflow import model_ops
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/ligand_ml/models/tensorflow/model_ops.py", line 11, in <module>
    import tensorflow.contrib.eager as tfe
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 33, in <module>
    from tensorflow.contrib import compiler
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/site-packages/tensorflow/contrib/compiler/__init__.py", line 22, in <module>
    from tensorflow.contrib.compiler import xla
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/site-packages/tensorflow/contrib/compiler/xla.py", line 22, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/private/var/lib/jenkins/workspace/ligand_ml_osx/anaconda/envs/ligand_ml/lib/python3.6/site-packages/tensorflow/python/estimator/__init__.py", line 26, in <module>
    from tensorflow_estimator.python import estimator
```

**Comment by jjhelmus** [comment]
Wait I see the issue, `tensorflow` does not pin to a version of `tensorflow-base`.  I'll remove the packages.

**Comment by jjhelmus** [comment]
I've moved the offending packages to the `broken` label.  It may take ~1 hour for the CDN network to pick up this change.

**Comment by lilleswing** [comment]
Thank you so much for a quick reply! That is amazing.

**Comment by njzjz** [comment]
Yes, last night I found the package will require `tensorflow-base` in the `anaconda` channel, so I pinned the version in https://github.com/conda-forge/tensorflow-feedstock/commit/acfffac852f1fb4d9ece18f4259e493abbdd5d1e. The package published this afternoon may pin to the correct version of `tensorflow-base`.
